apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: greeter-client
  name: greeter-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-client
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: greeter-client
    spec:
      containers:
      - image: jenniferstrej/greeter-client:8
        name: greeter-client
        env:
        - name: HOSTANDPORT
          value: "greeter-server:80"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeter-client
  name: greeter-client
spec:
  selector:
    app: greeter-client
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 50052