apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: greeter-server
  name: greeter-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: greeter-server
    spec:
      containers:
      - image: jenniferstrej/greeter-server:063d367d20dcb297442e13cbba68fc2f4fd6c98d
        name: greeter-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeter-server
  name: greeter-server
spec:
  type: LoadBalancer
  selector:
    app: greeter-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50051