apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: greeter-server
  name: greeter-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: greeter-server
    spec:
      containers:
      - image: jenniferstrej/greeter-server:703d2e0bd7f45dfdef69e1dbd16a6486d192f6a7
        name: greeter-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeter-server
  name: greeter-server
spec:
  type: LoadBalancer
  selector:
    app: greeter-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50051